/// 内置词库：100 个高频常用词（学习流与自定义词合并使用）。
library;

import 'models.dart';

const builtInWords = <WordItem>[
  WordItem('abandon', '/əˈbændən/', 'v. 放弃；抛弃'),
  WordItem('ability', '/əˈbɪləti/', 'n. 能力；才能'),
  WordItem('absorb', '/əbˈzɔːb/', 'v. 吸收；使专注'),
  WordItem('accept', '/əkˈsept/', 'v. 接受；同意'),
  WordItem('accident', '/ˈæksɪdənt/', 'n. 事故；意外'),
  WordItem('achieve', '/əˈtʃiːv/', 'v. 实现；达到'),
  WordItem('active', '/ˈæktɪv/', 'adj. 活跃的；积极的'),
  WordItem('actually', '/ˈæktʃuəli/', 'adv. 实际上；居然'),
  WordItem('adapt', '/əˈdæpt/', 'v. 适应；改编'),
  WordItem('address', '/əˈdres/', 'n. 地址 v. 处理'),
  WordItem('admire', '/ədˈmaɪə(r)/', 'v. 钦佩；欣赏'),
  WordItem('admit', '/ədˈmɪt/', 'v. 承认；准许进入'),
  WordItem('advice', '/ədˈvaɪs/', 'n. 建议；忠告'),
  WordItem('afford', '/əˈfɔːd/', 'v. 负担得起；提供'),
  WordItem('against', '/əˈɡenst/', 'prep. 反对；靠着'),
  WordItem('agree', '/əˈɡriː/', 'v. 同意；赞成'),
  WordItem('aim', '/eɪm/', 'n. 目标 v. 瞄准'),
  WordItem('allow', '/əˈlaʊ/', 'v. 允许；准许'),
  WordItem('although', '/ɔːlˈðəʊ/', 'conj. 虽然；尽管'),
  WordItem('amazing', '/əˈmeɪzɪŋ/', 'adj. 令人惊奇的'),
  WordItem('amount', '/əˈmaʊnt/', 'n. 数量；总额'),
  WordItem('ancient', '/ˈeɪnʃənt/', 'adj. 古代的；古老的'),
  WordItem('announce', '/əˈnaʊns/', 'v. 宣布；声明'),
  WordItem('anxious', '/ˈæŋkʃəs/', 'adj. 焦虑的；渴望的'),
  WordItem('apologize', '/əˈpɒlədʒaɪz/', 'v. 道歉'),
  WordItem('appear', '/əˈpɪə(r)/', 'v. 出现；似乎'),
  WordItem('apply', '/əˈplaɪ/', 'v. 申请；应用'),
  WordItem('appreciate', '/əˈpriːʃieɪt/', 'v. 感激；欣赏'),
  WordItem('approach', '/əˈprəʊtʃ/', 'v. 接近 n. 方法'),
  WordItem('argue', '/ˈɑːɡjuː/', 'v. 争论；主张'),
  WordItem('arrange', '/əˈreɪndʒ/', 'v. 安排；整理'),
  WordItem('arrive', '/əˈraɪv/', 'v. 到达；抵达'),
  WordItem('article', '/ˈɑːtɪkl/', 'n. 文章；物品'),
  WordItem('ashamed', '/əˈʃeɪmd/', 'adj. 羞愧的'),
  WordItem('assist', '/əˈsɪst/', 'v. 帮助；协助'),
  WordItem('assume', '/əˈsjuːm/', 'v. 假定；承担'),
  WordItem('attend', '/əˈtend/', 'v. 出席；照料'),
  WordItem('attitude', '/ˈætɪtjuːd/', 'n. 态度；看法'),
  WordItem('attract', '/əˈtrækt/', 'v. 吸引'),
  WordItem('average', '/ˈævərɪdʒ/', 'n. 平均 adj. 普通的'),
  WordItem('avoid', '/əˈvɔɪd/', 'v. 避免；避开'),
  WordItem('aware', '/əˈweə(r)/', 'adj. 意识到的'),
  WordItem('balance', '/ˈbæləns/', 'n. 平衡 v. 使平衡'),
  WordItem('behave', '/bɪˈheɪv/', 'v. 表现；举止'),
  WordItem('believe', '/bɪˈliːv/', 'v. 相信；认为'),
  WordItem('benefit', '/ˈbenɪfɪt/', 'n. 益处 v. 受益'),
  WordItem('beyond', '/bɪˈjɒnd/', 'prep. 超出；在…那边'),
  WordItem('borrow', '/ˈbɒrəʊ/', 'v. 借入；借用'),
  WordItem('brave', '/breɪv/', 'adj. 勇敢的'),
  WordItem('bright', '/braɪt/', 'adj. 明亮的；聪明的'),
  WordItem('calm', '/kɑːm/', 'adj. 平静的 v. 使平静'),
  WordItem('cancel', '/ˈkænsl/', 'v. 取消；撤销'),
  WordItem('capable', '/ˈkeɪpəbl/', 'adj. 有能力的'),
  WordItem('career', '/kəˈrɪə(r)/', 'n. 职业；生涯'),
  WordItem('careful', '/ˈkeəfl/', 'adj. 小心的；仔细的'),
  WordItem('celebrate', '/ˈselɪbreɪt/', 'v. 庆祝；赞美'),
  WordItem('certain', '/ˈsɜːtn/', 'adj. 确定的；某些'),
  WordItem('challenge', '/ˈtʃælɪndʒ/', 'n. 挑战 v. 向…挑战'),
  WordItem('chance', '/tʃɑːns/', 'n. 机会；可能性'),
  WordItem('change', '/tʃeɪndʒ/', 'v. 改变 n. 变化'),
  WordItem('charge', '/tʃɑːdʒ/', 'v. 收费；充电 n. 费用'),
  WordItem('cheer', '/tʃɪə(r)/', 'v. 欢呼；使高兴'),
  WordItem('choice', '/tʃɔɪs/', 'n. 选择；抉择'),
  WordItem('choose', '/tʃuːz/', 'v. 选择；挑选'),
  WordItem('clever', '/ˈklevə(r)/', 'adj. 聪明的；机灵的'),
  WordItem('collect', '/kəˈlekt/', 'v. 收集；聚集'),
  WordItem('comfort', '/ˈkʌmfət/', 'n. 安慰；舒适 v. 安慰'),
  WordItem('common', '/ˈkɒmən/', 'adj. 常见的；共同的'),
  WordItem('communicate', '/kəˈmjuːnɪkeɪt/', 'v. 交流；沟通'),
  WordItem('compare', '/kəmˈpeə(r)/', 'v. 比较；对照'),
  WordItem('complete', '/kəmˈpliːt/', 'v. 完成 adj. 完整的'),
  WordItem('concern', '/kənˈsɜːn/', 'n. 关心；担忧 v. 涉及'),
  WordItem('confident', '/ˈkɒnfɪdənt/', 'adj. 自信的；确信的'),
  WordItem('consider', '/kənˈsɪdə(r)/', 'v. 考虑；认为'),
  WordItem('contain', '/kənˈteɪn/', 'v. 包含；容纳'),
  WordItem('continue', '/kənˈtɪnjuː/', 'v. 继续；持续'),
  WordItem('control', '/kənˈtrəʊl/', 'v. 控制 n. 控制权'),
  WordItem('convince', '/kənˈvɪns/', 'v. 使确信；说服'),
  WordItem('courage', '/ˈkʌrɪdʒ/', 'n. 勇气；胆量'),
  WordItem('create', '/kriˈeɪt/', 'v. 创造；创建'),
  WordItem('curious', '/ˈkjʊəriəs/', 'adj. 好奇的'),
  WordItem('decide', '/dɪˈsaɪd/', 'v. 决定；下决心'),
  WordItem('deliver', '/dɪˈlɪvə(r)/', 'v. 递送；发表'),
  WordItem('demand', '/dɪˈmɑːnd/', 'v. 要求 n. 需求'),
  WordItem('describe', '/dɪˈskraɪb/', 'v. 描述；形容'),
  WordItem('deserve', '/dɪˈzɜːv/', 'v. 应得；值得'),
  WordItem('develop', '/dɪˈveləp/', 'v. 发展；开发'),
  WordItem('difference', '/ˈdɪfrəns/', 'n. 差别；不同'),
  WordItem('difficult', '/ˈdɪfɪkəlt/', 'adj. 困难的'),
  WordItem('discover', '/dɪˈskʌvə(r)/', 'v. 发现；发觉'),
  WordItem('discuss', '/dɪˈskʌs/', 'v. 讨论；商量'),
  WordItem('disease', '/dɪˈziːz/', 'n. 疾病'),
  WordItem('distance', '/ˈdɪstəns/', 'n. 距离；远方'),
  WordItem('double', '/ˈdʌbl/', 'adj. 双的 adv. 两倍'),
  WordItem('doubt', '/daʊt/', 'n. 怀疑 v. 不确定'),
  WordItem('eager', '/ˈiːɡə(r)/', 'adj. 渴望的；热切的'),
  WordItem('earn', '/ɜːn/', 'v. 赚得；挣得'),
  WordItem('effort', '/ˈefət/', 'n. 努力；尝试'),
  WordItem('encourage', '/ɪnˈkʌrɪdʒ/', 'v. 鼓励；激励'),
];
